### ISSUE TITLE
Agent-branch previews still build on Vercel — ignoreCommand is not taking effect

### ISSUE THREAD

**Issue by parthalon025** [parthalon025/six-flags-sa#757]
## What failed

The vercel-previews policy promises that `claude/*`, `worktree-*` and `cursor/*` branches never build a preview unless the user directs it. They are all still building, drawing from the 100/day account budget the policy exists to protect.

Of the 20 most recent deployments, these agent-branch previews all built (and all errored):

- `claude/e2e-tests-map-viz-ljr3nn`
- `claude/issues-org-agent-mega-prs-mnz3n5-factory`
- `claude/issues-org-agent-mega-prs-mnz3n5-app`
- `claude/issues-org-agent-mega-prs-mnz3n5-automations`
- `claude/factory-development-status-cc21re` (×4)
- `worktree-fix-24-critical-paths-gate` (×2)
- `worktree-catalog-allow-no-heights` (×2)
- `worktree-fix-694-contribution-fk`, `worktree-fix-401-top100-app-build`, `worktree-fix-12-watercolor-status`

## The decision logic is correct

`scripts/lib/vercel-ignore.mjs` gets it right. Run with the exact env of the deployment that built:

```
VERCEL_ENV=preview \
VERCEL_GIT_COMMIT_REF=claude/e2e-tests-map-viz-ljr3nn \
VERCEL_GIT_COMMIT_SHA=ce97224 \
node scripts/lib/vercel-ignore.mjs
```

```
agent preview branch claude/e2e-tests-map-viz-ljr3nn — skipping
  (user reserve: add [vercel build] or VERCEL_USER_BUILD=1)
EXIT=0 (0=skip)
```

`AGENT_PREVIEW_BRANCH` is `/^(worktree-|cursor\/|claude\/)/` and matches. `vercel.json` wires `"ignoreCommand": "bash scripts/vercel-ignore.sh"`. The script exits 0, which Vercel reads as skip.

So the logic is not the bug — the ignoreCommand is not running, or its result is not being honoured.

## Suggested direction

Most likely the Vercel **project setting** for "Ignored Build Step" is set in the dashboard, which takes precedence over `vercel.json`'s `ignoreCommand`. Worth confirming in project settings; a Root Directory setting that makes `scripts/vercel-ignore.sh` unreachable from the build cwd would do it too.

Only the account owner can check or change the dashboard setting, so this needs a human.

## Impact

Non-blocking for any single PR, but it is a standing budget leak: every agent push consumes a deployment from the shared 100/day pool, which is the exact failure `9ab3c87` ("stops `claude/*` branches burning the Vercel preview budget") set out to fix. That commit fixed the pattern; the pattern is not being consulted.

Note these previews are also all failing for the unrelated reason in #756, so right now the leak costs budget and produces nothing.

**Comment by parthalon025** [comment]
## Root cause found — it is not a dashboard setting

`vercel.json`'s `ignoreCommand` **is** running. It crashes, and `vercel-ignore.sh` fails open. From the build log of `dpl_6UA5UV2F2q3Sgbap8oyeZqHzrnve`:

```
Found .vercelignore
Removed 1066 ignored files defined in .vercelignore
...
Running "bash scripts/vercel-ignore.sh"
VERCEL_ENV=preview
VERCEL_GIT_COMMIT_REF=claude/e2e-tests-map-viz-ljr3nn
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/vercel/path0/scripts/lib/git-env.mjs'
  imported from /vercel/path0/scripts/lib/vercel-ignore.mjs
Node.js v24.19.0
Proceeding with build.
```

`.vercelignore` excludes `scripts/**` and allowlists individual files under `scripts/lib/`. `scripts/lib/vercel-ignore.mjs` imports `scrubGitEnv` from `./git-env.mjs`, and that file is the one import in its closure with no allowlist entry:

| import | allowlisted |
| --- | --- |
| `app-paths.mjs` | ✅ |
| **`git-env.mjs`** | ❌ |
| `gitnexus-only.mjs` | ✅ |
| `production-postgres-guard.mjs` | ✅ |
| `production-redis-guard.mjs` | ✅ |
| `vercel-budget.mjs` | ✅ |
| `vercel-deploy-gate.mjs` | ✅ |
| `version-stamp.mjs` | ✅ |

So the file is stripped from the upload, the script dies, and `scripts/vercel-ignore.sh` reaches its last branch:

```sh
echo "Ignore decision failed (exit $code) — proceeding with build."
exit 1
```

Failing open is the right default for a broken ignore script — you would rather over-build than silently skip a production deploy. But it means the branch skip has been dead since `git-env.mjs` was extracted, and nothing said so.

## Proposed patch

```diff
 !scripts/lib/vercel-ignore.mjs
+!scripts/lib/git-env.mjs
 !scripts/lib/vercel-budget.mjs
```

## Worth considering alongside

Two things would have caught this and would stop it recurring:

1. **A test that the allowlist covers the closure.** `scripts/lib/vercel-ignore.mjs`'s import graph is walkable; a `test/scripts/*.test.mjs` asserting every entry in it has a `.vercelignore` allowlist line would fail the day someone extracts another helper. The same check applies to the `packages/venue-builder/lib/delivery/**` closure in #756.
2. **The fail-open branch is silent in practice.** It prints, but nothing reads the print. Since the categorical skip is a budget control, a crash there costs deployments — worth deciding whether that branch should keep failing open or hard-fail loudly.

Not fixing here: unrelated to the PR this surfaced on (#755), per the agent-handoff policy.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by parthalon025** [comment]
Fixed and shipped in #759 (merged as `d74b406c`). Agent previews now skip correctly — confirmed on a live build.

## It was not the dashboard setting, and it did not need you

This issue concluded *"most likely the Vercel project setting for Ignored Build Step is set in the dashboard… only the account owner can check or change it, so this needs a human."* That would have sent the owner into project settings for a bug that was in the repo.

The analysis here was right that the decision logic is correct — running `vercel-ignore.mjs` locally does print `skipping`. The reason it never happened on Vercel is that **the script crashed before that logic ran**:

```
Running "bash scripts/vercel-ignore.sh"
VERCEL_ENV=preview
VERCEL_GIT_COMMIT_REF=claude/issues-org-agent-mega-prs-mnz3n5-deploy-hygiene
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/vercel/path0/scripts/lib/git-env.mjs'
  imported from /vercel/path0/scripts/lib/vercel-ignore.mjs
```

`.vercelignore` excludes `scripts/**` with a hand-listed allowlist, and `scripts/lib/git-env.mjs` — a direct import of `vercel-ignore.mjs` — was not on it. So the ignoreCommand died at import time on every deployment, Vercel failed open, and every preview built. Locally it works because the file is present; the failure only exists in the uploaded tree. Same root cause class as #756, one directory over.

That is why `9ab3c87` appeared not to work: the pattern was consulted, but the module carrying it never loaded.

## A second, genuine defect underneath

Once the script could load, there was still a real bug: `decideVercelBuild` checked `files == null → {build: true, category: 'unknown-diff'}` **before** `isAgentPreviewBranch`, so an unreadable diff failed open. Fixed by moving the branch check above it — `commitSubjectWantsSkip` and user-directed `[vercel build]` still take precedence, so the 25/day user reserve is unaffected.

Also fixed: `scripts/lib/release-bump.mjs`, imported by `bump-version.mjs`, missing the same way — a latent crash in the version bump.

## Proof

```
Checking if Vercel build is needed...
Git ref: claude/issues-org-agent-mega-prs-mnz3n5-deploy-hygiene
Budget: 25 user-reserved, ~75 automation
agent preview branch claude/… — skipping (user reserve: add [vercel build] or VERCEL_USER_BUILD=1)
Skipping build.
The Deployment has been canceled as a result of running the command defined in the "Ignored Build Step" setting.
```

Reported on the PR as `Vercel: success — "Canceled by Ignored Build Step"`, so a skip now reads as a pass rather than a failure.

The `scripts/` block is also covered by the derived import-closure test now, so the next added import cannot silently break the ignoreCommand again.

Closing as completed. No dashboard change needed.

---
_Generated by [Claude Code](https://claude.ai/code)_
